services:
  - type: web
    name: coffee-shop
    env: java
    plan: free
    buildCommand: ./gradlew clean build -x test
    startCommand: java -jar build/libs/*.jar
    envVars:
      - key: SPRING_DATASOURCE_URL
        fromDatabase:
          name: coffee-db
          property: connectionString
databases:
  - name: coffee-db
    plan: free
